# Generated by Django 4.0.10 on 2024-07-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quntity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
