# Generated by Django 4.0.10 on 2024-07-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_quntity_as_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quntity_as_float',
            new_name='quantity_as_float',
        ),
    ]
